### Create Account
post http://localhost:5000/auth/register
content-type: application/json

{
    "fullName":"Chamberlain",
    "email":"newUser008@gmail.com",
    "password":"asdf1234"
}

### User Login
post http://localhost:5000/auth/login
content-type: application/json

{
    "email":"newUser001@gmail.com",
    "password":"asdf1234"
}

### Create Account
post http://localhost:5000/auth/login
content-type: application/json

{
    "fullName":"Patrick Christian",
    "email":"newUser005@gmail.com",
    "password":"asdf1234"
}

###
GET http://localhost:5000/users/

###
put http://localhost:5000/users/cbb3f94e-1c67-40ab-9dac-c7b2d2aefa20
content-type: application/json

{
    "password":"asdf1235"
}

### create task
post http://localhost:5000/tasks/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxOTJhYzE1Ny0zYzFiLTQ3MTItYjQzNy01NmM2ZWVjMDA5MjgiLCJlbWFpbCI6Im5ld1VzZXIwMDVAZ21haWwuY29tIiwiaWF0IjoxNzUwNDE2OTYyLCJleHAiOjE3NTA0MjA1NjJ9.lMvJmf7274s4NJ-HxGEQprtGwfmzc0fTEuex7utFTCA

{
    "title":"trading routine",
    "description":"check the trades that have either been triggered, TP OR SL",
    "isDone":false
}

### 
post http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"newUser008@gmail.com",
    "password":"asdf1234"
}
